package onig

type RegexOptions uint

/* options */
const REGEX_OPTION_NONE RegexOptions = 0

/* options (compile time) */
const REGEX_OPTION_IGNORECASE RegexOptions = 1
const REGEX_OPTION_EXTEND = (REGEX_OPTION_IGNORECASE << 1)
const REGEX_OPTION_MULTILINE = (REGEX_OPTION_EXTEND << 1)
const REGEX_OPTION_SINGLELINE = (REGEX_OPTION_MULTILINE << 1)
const REGEX_OPTION_FIND_LONGEST = (REGEX_OPTION_SINGLELINE << 1)
const REGEX_OPTION_FIND_NOT_EMPTY = (REGEX_OPTION_FIND_LONGEST << 1)
const REGEX_OPTION_NEGATE_SINGLELINE = (REGEX_OPTION_FIND_NOT_EMPTY << 1)
const REGEX_OPTION_DONT_CAPTURE_GROUP = (REGEX_OPTION_NEGATE_SINGLELINE << 1)
const REGEX_OPTION_CAPTURE_GROUP = (REGEX_OPTION_DONT_CAPTURE_GROUP << 1)

/* options (search time) */
const REGEX_OPTION_NOTBOL = (REGEX_OPTION_CAPTURE_GROUP << 1)
const REGEX_OPTION_NOTEOL = (REGEX_OPTION_NOTBOL << 1)
const REGEX_OPTION_POSIX_REGION = (REGEX_OPTION_NOTEOL << 1)
const REGEX_OPTION_CHECK_VALIDITY_OF_STRING = (REGEX_OPTION_POSIX_REGION << 1)

/* options (compile time) */
const REGEX_OPTION_IGNORECASE_IS_ASCII = (REGEX_OPTION_CHECK_VALIDITY_OF_STRING << 3)
const REGEX_OPTION_WORD_IS_ASCII = (REGEX_OPTION_IGNORECASE_IS_ASCII << 1)
const REGEX_OPTION_DIGIT_IS_ASCII = (REGEX_OPTION_WORD_IS_ASCII << 1)
const REGEX_OPTION_SPACE_IS_ASCII = (REGEX_OPTION_DIGIT_IS_ASCII << 1)
const REGEX_OPTION_POSIX_IS_ASCII = (REGEX_OPTION_SPACE_IS_ASCII << 1)
const REGEX_OPTION_TEXT_SEGMENT_EXTENDED_GRAPHEME_CLUSTER = (REGEX_OPTION_POSIX_IS_ASCII << 1)
const REGEX_OPTION_TEXT_SEGMENT_WORD = (REGEX_OPTION_TEXT_SEGMENT_EXTENDED_GRAPHEME_CLUSTER << 1)

/* options (search time) */
const REGEX_OPTION_NOT_BEGIN_STRING = (REGEX_OPTION_TEXT_SEGMENT_WORD << 1)
const REGEX_OPTION_NOT_END_STRING = (REGEX_OPTION_NOT_BEGIN_STRING << 1)
const REGEX_OPTION_NOT_BEGIN_POSITION = (REGEX_OPTION_NOT_END_STRING << 1)
const REGEX_OPTION_CALLBACK_EACH_MATCH = (REGEX_OPTION_NOT_BEGIN_POSITION << 1)
const REGEX_OPTION_MATCH_WHOLE_STRING = (REGEX_OPTION_CALLBACK_EACH_MATCH << 1)

const REGEX_OPTION_MAXBIT = REGEX_OPTION_MATCH_WHOLE_STRING
